### ISSUE TITLE
Model Testing

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos22io#2]
This model is ready for testing!

**Comment by pauline-banye** [comment]
Hi @GemmaTuron 
### MODEL TEST FOR EOS935D

## CLI
- [x] Model eos935d fetched, served and ran successfully on the CLI.
- [X] Model was tested using a list of smiles and a single smile string
[eos22io_fetch.log](https://github.com/ersilia-os/eos22io/files/10856061/eos22io_fetch.log)
[eos22io_run.csv](https://github.com/ersilia-os/eos22io/files/10856066/eos22io_run.csv)

## Note
I noticed that the model does not return a probability when a single string is passed.
[eos22io_list_run.csv](https://github.com/ersilia-os/eos22io/files/10856078/eos22io_list_run.csv)


## COLAB
- [x]  Model eos935d fetched, served and ran successfully on colab
[eos22io_output.csv](https://github.com/ersilia-os/eos22io/files/10856951/eos22io_output.csv)
https://colab.research.google.com/drive/1YjwAG1vgWuKCbJ8kkEWPM-b7hbbC_Jhf?usp=sharing

**Comment by paulinebanye** [comment]
Hi @GemmaTuron 
### MODEL TEST FOR EOS22IO

## CLI
- [x] Model eos22io fetched, served and ran successfully on the CLI.
- [X] Model was tested using a list of smiles and a single smile string
[eos22io_fetch.log](https://github.com/ersilia-os/eos22io/files/10856061/eos22io_fetch.log)
[eos22io_run.csv](https://github.com/ersilia-os/eos22io/files/10856066/eos22io_run.csv)

*Note
I noticed that the model does not return a probability when a single string is passed.
[eos22io_list_run.csv](https://github.com/ersilia-os/eos22io/files/10856078/eos22io_list_run.csv)


## COLAB
- [x]  Model eos22io fetched, served and ran successfully on colab
[eos22io_output.csv](https://github.com/ersilia-os/eos22io/files/10856951/eos22io_output.csv)
https://colab.research.google.com/drive/1YjwAG1vgWuKCbJ8kkEWPM-b7hbbC_Jhf?usp=sharing

**Comment by GemmaTuron** [comment]
oh thanks @pauline-banye !

@DhanshreeA can you confirm if that's the case for you as well?
and @carcablop any insight into why this might be happening?

**Comment by DhanshreeA** [comment]
Checking @GemmaTuron 
However the interpretation of the model does mention that for inorganic compounds and salts, the model returns nothing. The compound that @pauline-banye tested is [this](https://pubchem.ncbi.nlm.nih.gov/compound/4-Aminoisoxazolidin-3-one) I did try to read up on it but I understood very little and am unable to categorize it. Maybe you could verify if it falls within that category?

**Comment by GemmaTuron** [comment]
thanks for the catch @DhanshreeA 
The molecule is probably too small, though it is not an inorganic compound (has Carbon and Hidrogen) and does not have salts. Can you try with another one?

**Comment by DhanshreeA** [comment]
@GemmaTuron  Just tested the model on my local, it is in fact not working with a single input. The molecule @pauline-banye tested it with does get a (low) value and when a compound is out of scope, like Calcium Hidride (inorganic salt) gets a Nan instead of nothing (which is what is happening in the single smile case)

Output attached:
[eos22io_output_1.csv](https://github.com/ersilia-os/eos22io/files/10860251/eos22io_output_1.csv)
[eos22io_output.csv](https://github.com/ersilia-os/eos22io/files/10860252/eos22io_output.csv)


The model works fine on local and Colab otherwise.

[eos22io_colab_output.csv](https://github.com/ersilia-os/eos22io/files/10860505/eos22io_colab_output.csv)

**Comment by GemmaTuron** [comment]
Thanks @DhanshreeA 
I'm tagging here @carcablop so she can have a look and maybe identify the issue

**Comment by carcablop** [comment]
Hello @DhanshreeA, @pauline-banye  and @GemmaTuron .
Thank you so much for this information. I will debug more.

**Comment by paulinebanye** [comment]
> Hello @DhanshreeA, @pauline-banye and @GemmaTuron . Thank you so much for this information. I will debug more.

You're welcome @carcablop

**Comment by carcablop** [comment]
Hello @GemmaTuron .
The problem to run the model passing a molecule was being a problem of the model that did not accept a single molecule per input.
More specifically the error was giving in this line of code:
```

/usr/local/envs/eos22io/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'AttentiveFP.AttentiveLayers.Fingerprint' has changed. Saved a reverse patch to Fingerprint.patch. Run `patch -p0 < Fingerprint.patch` to revert your changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/envs/eos22io/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. Saved a reverse patch to Linear.patch. Run `patch -p0 < Linear.patch` to revert your changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/envs/eos22io/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. Saved a reverse patch to ModuleList.patch. Run `patch -p0 < ModuleList.patch` to revert your changes.
  warnings.warn(msg, SourceChangeWarning)
feature dicts file saved as /tmp/eos-7s7zz6ct/_data.pickle
0 compounds cannot be featured
Traceback (most recent call last):
  File "/root/bentoml/repository/eos22io/20230304153440_4A2250/eos22io/artifacts/framework/code/main.py", line 120, in <module>
    output=my_model(smiles_list)
  File "/root/bentoml/repository/eos22io/20230304153440_4A2250/eos22io/artifacts/framework/code/main.py", line 99, in my_model
    remain_pred_list = eval(model, remained_df,feature_dicts)
  File "/root/eos/repository/eos22io/20230304153440_4A2250/eos22io/artifacts/framework/code/idl_ppb_/idl_ppb_modular.py", line 85, in eval
    y_pred_list.extend(np.array(mol_prediction.data.squeeze().cpu().numpy()))
TypeError: iteration over a 0-d array
```
To solve it, the axis=1 was passed as an argument to the function squeeze
` y_pred_list.extend(np.array(mol_prediction.data.squeeze(axis=1).cpu().numpy()))`

The model is ready to be tested again.

**Comment by GemmaTuron** [comment]
thanks @carcablop !!

**Comment by carcablop** [comment]
Hi @GemmaTuron 
The model run sucessfully in my CLI. 
I am attaching the output files for one molecule as input, a list of molecules as input, and the entire eml_canonical file as input.
These are the outputs: 
[out.csv](https://github.com/ersilia-os/eos22io/files/10933283/out.csv)
[out_completa.csv](https://github.com/ersilia-os/eos22io/files/10933287/out_completa.csv)
