### ISSUE TITLE
Clean UP & Dockerization eos22io

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos22io#5]
Please refactor this model so it is updated to the latest version of the eos template

**Comment by emmakodes** [comment]
Hello @GemmaTuron When I test the model:
- pip install torch==1.5.0 torchvision==0.6.0 fails on this model:
```
Collecting torch==1.5.0
  Downloading torch-1.5.0-cp37-cp37m-manylinux1_x86_64.whl (752.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━      659.6/752.0 MB 9.1 MB/s eta 0:00:11
ERROR: Wheel 'torch' located at /tmp/pip-unpack-x9q103gq/torch-1.5.0-cp37-cp37m-manylinux1_x86_64.whl is invalid.
```
I had to install torch without specifying version then I got version the version by running `pip list`  `pip install torch==1.13.1 torchvision==0.14.1` works for this model



- `conda install openbabel=2.4.1 -c conda-forge` fails for linux/arm64.
```
#25 1250.0 PackagesNotFoundError: The following packages are not available from current channels:
#25 1250.0 
#25 1250.0   - openbabel=2.4.1
#25 1250.0 
#25 1250.0 Current channels:
#25 1250.0 
#25 1250.0   - https://conda.anaconda.org/conda-forge/linux-aarch64
#25 1250.0   - https://conda.anaconda.org/conda-forge/noarch
#25 1250.0   - https://repo.anaconda.com/pkgs/main/linux-aarch64
#25 1250.0   - https://repo.anaconda.com/pkgs/main/noarch
#25 1250.0   - https://repo.anaconda.com/pkgs/r/linux-aarch64
#25 1250.0   - https://repo.anaconda.com/pkgs/r/noarch
#25 1250.0 
#25 1250.0 To search for alternate channels that may provide the conda package you're
#25 1250.0 looking for, navigate to
#25 1250.0 
#25 1250.0     https://anaconda.org/
#25 1250.0 
#25 1250.0 and use the search bar at the top of the page.
```
I tried to look for a compatible version for linux/arm64. I see that `conda install -c conda-forge openbabel` seems to be supported on linux/arm64 [here](https://anaconda.org/conda-forge/openbabel) but then when I install, it resulted in dependency conflict.
<br><br>
- Currently `pip install torch==1.13.1 torchvision==0.14.1` works for this model(both linux/amd64 and linux/arm64)
-  `conda install openbabel=2.4.1 -c conda-forge` works for only linux/amd64
With `pip install torch==1.13.1 torchvision==0.14.1` and `conda install openbabel=2.4.1 -c conda-forge`  model fetch successfully and makes prediction 
[eos22io_output.csv](https://github.com/ersilia-os/eos22io/files/11844473/eos22io_output.3.csv)
[eos22io_fetch_log.txt](https://github.com/ersilia-os/eos22io/files/11844514/eos22io_fetch_log.txt)

**Comment by GemmaTuron** [comment]
thanks @emmakodes !

Please open a Pr so we can merge the changes

**Comment by emmakodes** [comment]
Okay @GemmaTuron
